{% set name = "rubin-scheduler" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0791bce2bd4ea989dec5e9afc143b267c2b3284744afb3c1bd38a167b8a1f84a

build:
  entry_points:
    - scheduler_download_data = rubin_scheduler.data.scheduler_download_data:scheduler_download_data
    - rs_download_sky = rubin_scheduler.data.rs_download_sky:rs_download_sky
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm <8.0
    - pip
  run:
    - python >=3.9
    - numpy
    - matplotlib-base
    - healpy
    - pandas
    - numexpr
    - scipy
    - astroplan
    - astropy
    - pytables
    - h5py
    - requests
    - shapely
    - tqdm
    - gitpython
    - conda

test:
  imports:
    - rubin_scheduler
  commands:
    - scheduler_download_data --help
    - rs_download_sky --help
  requires:
    - pip

about:
  home: https://github.com/lsst/rubin_scheduler
  summary: Scheduling algorithms for Vera C. Rubin Observatory's Legacy Survey of Space and Time (LSST).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhiannonlynne
