{% set name = "rubin-scheduler" %}
{% set version = "0.1.2a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubin-scheduler-{{ version }}.tar.gz
  sha256: 0afb78ef45ccf4549a4b31d54b3b810290c6b8f651d33e26ecc1acf1c8684136

build:
  entry_points:
    - scheduler_download_data = rubin_scheduler.data.scheduler_download_data:scheduler_download_data
    - rs_download_sky = rubin_scheduler.data.rs_download_sky:rs_download_sky
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm <8.0
    - pip
  run:
    - python >=3.7
    - numpy
    - matplotlib-base
    - healpy
    - numexpr
    - scipy
    - astropy
    - pytables
    - h5py
    - requests
    - shapely
    - tqdm

test:
  imports:
    - rubin_scheduler
  commands:
    - pip check
    - scheduler_download_data --help
    - rs_download_sky --help
  requires:
    - pip

about:
  home: https://github.com/lsst/rubin_scheduler
  summary: Scheduling algorithms for Vera C. Rubin Observatory's Legacy Survey of Space and Time (LSST).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhiannonlynne
